[package]
name = "exspeed-streams"
version = "0.7.0"
edition = "2021"

[dependencies]
exspeed-common = { path = "../exspeed-common" }
bytes = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
