{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "exspeed.fullname" . }}
  labels:
    {{- include "exspeed.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels: {{- include "exspeed.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.tls.secretName }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      {{- end }}
      {{- if .Values.metricsTokenSecret }}
      authorization:
        type: Bearer
        credentials:
          name: {{ .Values.metricsTokenSecret }}
          key: token
      {{- end }}
{{- end }}
